# Generated by Django 4.2.7 on 2025-06-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='users/avatars/', verbose_name='Аватар'),
        ),
    ]
